#!/bin/ksh

# todo: change type names
#		function loader
#		version/profile
#		GLhandleARB
#		compatibility
#		<remove>

cat $1 | sed 's/ comment=".*"//g' | awk '
	/<enum /{split($3,n,"="); split($2,v,"=");
	print "#define " substr(n[2],2,length(n[2])-2) " " substr(v[2],2,length(v[2])-2)}' > tmp

sed -i 's|"/||g' tmp 
sed -i '/* */d; /.*  .*/d' tmp 


cat $1 | sed 's/ group=".*"//g; s/ class=".*"//g; s/ len=".*"//g; s/const //g; s/<name>//g' | awk '
	/<proto>void/{printf "void " "(*" substr($2,1,length($2)-15) ")("};
	/<proto><ptype>/{printf substr($1,15,length($1)-22) " " "(*" substr($2,1,length($2)-15) ")("}
	/<param/{printf substr($1,15,length($1)-22) " " substr($2,1,length($2)-15) ", "};
	/<[/]command>/{print ")" }' >> tmp 

sed -i 's/>/*/g; s/const//g; s/, )/);/g; s/,  [*]/, void */g' tmp
sed -i '
	s/GLuint/uint/g;
	s/GLboolean/uchar/g;
	s/GLbitfield/uint/g;
	s/GLbyte/char/g;
	s/GLubyte/uchar/g;
	s/GLshort/short/g;
	s/GLushort/ushort/g;
	s/GLint/int/g;
	s/GLclampx/int/g;
	s/GLsizei/int/g;
	s/GLfloat/float/g;
	s/GLclampf/float/g;
	s/GLdouble/double/g;
	s/GLclampd/double/g;
	s/GLeglClientBufferEXT/void*/g;
	s/GLeglImageOES/void*/g;
	s/GLchar/char/g;
	s/GLcharARB/char/g' tmp

delcomp(){
	i=$1
	for i in $(jot $i);
	do
		echo yoo
	cat tmp2 | sed '1,/SECTION: GL API interface /d' | sed '/profile="compatibility"/,${d;/<[/]require>/q;}'  
	done
}

n=$(cat $1 | sed '1,/SECTION: GL API interface /d' | grep 'profile="compatibility"' | wc -l) 
cat $1 | sed '1,/SECTION: GL API interface /d' > tmp2 
delcomp $n 
#cat $1 | sed '1,/SECTION: GL API interface /d' | sed '/profile="compatibility"/,${d;/<[/]require>/q;}' 
#sed -i '/profile="compatibility"/,/<[/]require>/{/profile="compatibility"/!{/<[/]require>/d;};}' tmp2
